#!/usr/bin/env tclsh
# build.tcl -- build the tkprintcompat .tm
# Pure Tcl, no external packages needed.
# Usage: tclsh build.tcl

set VERSION "0.3"
set TARGET  "tkprintcompat-${VERSION}.tm"
set srcdir  [file join [file dirname [info script]] src]

# read a file
proc readfile {path} {
    set fd [open $path r]
    fconfigure $fd -encoding utf-8
    set data [read $fd]
    close $fd
    return $data
}

# write a file
proc writefile {path data} {
    set fd [open $path w]
    fconfigure $fd -encoding utf-8
    puts -nonewline $fd $data
    close $fd
}

# read source files
set newtcl   [readfile [file join $srcdir newtcl8790.tcl]]
set printtcl [readfile [file join $srcdir print.tcl]]
set erw      [readfile [file join $srcdir print-8.6erw.tcl]]

# remove \f\nreturn\n from print.tcl
# the Tk-internal return would abort all subsequent fixes
set marker "\f\nreturn\n"
if {[string first $marker $printtcl] >= 0} {
    set printtcl [string map [list $marker "\n# <return removed>\n"] $printtcl]
} else {
    puts stderr "WARNING: '\\f\\nreturn\\n' not found in print.tcl!"
    puts stderr "         Please check whether print.tcl is current."
}

# load print.tcl only under Tcl 8.6
set print_wrapped "# print.tcl loaded only under Tcl 8.6
# Under Tcl 9 tk print is built in -- print.tcl would override it
if {!\[package vsatisfies \[info tclversion\] 9.0-\]} {

${printtcl}
}
"

# header
set datum [clock format [clock seconds] -format "%Y-%m-%d"]
set header "[join [list \
    "# tkprintcompat-${VERSION}.tm -- Tk print compatibility library" \
    {# Automatically generated by build.tcl from:} \
    {#   src/newtcl8790.tcl   -- ::tk::msgcat shim + Tcl 8.7/9 procs missing in 8.6} \
    {#   src/print.tcl        -- Tk 9.0 library/print.tcl (loaded only under Tcl 8.6)} \
    {#   src/print-8.6erw.tcl -- wrapper + fixes + package provide} \
    {#} \
    {# Under Tcl 9.0.3+: tk print is built in, only the Windows fixes are applied.} \
    {# Under Tcl 8.6 Linux:   CUPS via ::tk::print::cups} \
    {# Under Tcl 8.6 Windows: printer + gdi (Michael I. Schwartz)} \
    {#} \
    "# Build: $datum" \
    {# print.tcl source: Tk 9.0.4 library/print.tcl (verbatim)} \
] \n]\n\n"

# assemble
set content $header
append content $newtcl "\n"
append content $print_wrapped "\n"
append content $erw

writefile $TARGET $content

set lines [llength [split $content \n]]
puts "OK: $TARGET ($lines Zeilen)"
